accountapp/urls.py
from django.contrib.auth.views import LoginView, LogoutView
from django.urls import path

from accountapp.views import hello_world, AccountCreateView, AccountDetailView, AccountUpdateView, AccountDeleteView

app_name = 'accountapp'

urlpatterns = [
    path('hello_world/', hello_world, name='hello_world'),

    path('login/', LoginView.as_view(template_name='accountapp/login.html'),
         name='login'),
    path('logout/', LogoutView.as_view(), name='logout'),

    path('create/', AccountCreateView.as_view(), name='create'),
    path('detail/<int:pk>', AccountDetailView.as_view(), name='detail'),
    path('update/<int:pk>', AccountUpdateView.as_view(), name='update'),
    path('delete/<int:pk>', AccountDeleteView.as_view(), name='delete'),
]

gisjh_1/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('accounts/', include('accountapp.urls')),
    path('profiles/', include('profileapp.urls')),
    path('articles/', include('articlesapp.urls')),
    path('comments/', include('commentapp.urls')),


] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

templates/base.html
<!DOCTYPE html>
<html lang="en">
{% include 'head.html' %}
<head>
    <meta charset="UTF-8">
    <title>Title</title>
</head>



<body style="font_family:'NanumSquareR'">
{% include 'header.html' %}

<hr>
{% block content %}
{% endblock %}
</hr>
{% include 'footer.html' %}

</body>



</html>

templates/footer.html
<div style="text-align: center" >

    <div class = "jh_footer_button">
        <span>공지사항</span>
        <span>제휴문의</span>
        <span>서비스소개</span>

    </div>

    <div>
        <h6>JH</h6>
    </div>



</div>

templates/head.html
{% load static %}

<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-widrh, initial-scale=1, shrick-to-fit=no">
    <title>Title</title>

    {#boots strap link#}
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.1.3/css/bootstrap.min.css" integrity="sha384-MCw98/SFnGE8fJT3GXwEOngsV7Zt27NXFoaoApmYm81iuXoPkFOJwJ8ERdknLPMO" crossorigin="anonymous">
    {# GOOGLE FONTLINK  #}
    <link rel="preconnect" href="https://fonts.googleapis.com">
    <link rel="preconnect" href="https://fonts.gstatic.com" crossorigin>
    <link href="https://fonts.googleapis.com/css2?family=Libre+Barcode+39+Extended&family=Nosifer&display=swap" rel="stylesheet">

    {# STATIC FILES LINK   #}
    <link rel="stylesheet" type="text/css" href="{% static 'base.css' %}">


    {#  MATERIAL ICONS LINK  #}
    <link href="https://fonts.googleapis.com/css2?family=Material+Icons"
      rel="stylesheet">

    <style>
        @font-face {
            font-family: 'NanumSquareR';
            src: local('NanumSquareR'),
            url("{% static 'fonts/NanumSquareR.otf' %}") format("opentype");
        }
        @font-face {
            font-family: 'NanumSquareEB';
            src: local('NanumSquareEB'),
            url("{% static 'fonts/NanumSquareEB.otf' %}") format("opentype");
        }
        @font-face {
            font-family: 'NanumSquareB';
            src: local('NanumSquareB'),
            url("{% static 'fonts/NanumSquareB.otf' %}") format("opentype");
        }
        @font-face {
            font-family: 'NanumSquareR';
            src: local('NanumSquareR'),
            url("{% static 'fonts/NanumSquareR.otf' %}") format("opentype");
        }
    </style>


</head>

templates/header.html
<div style="text-align : center">

    <div class = "jh_header_logo">

        <h1>JH'S IMAGE STORE</h1>
    </div>

    <div class = "jh_header_button">
        <span>nav1</span>
        <span>nav2</span>

        {%  if not user.is_authenticated %}


        <span>
            <a href="{% url 'accountapp:login' %}" >
                Log in
            </a>

        </span>

        <span>
            <a href="{% url 'accountapp:create' %}" >
                Sign up
            </a>

        </span>

        {% else %}

        <span>
        
            <a href="{% url 'accountapp:detail' pk=user.pk %}">
                Mypage
            </a>

        </span>
        <span>

            <a href="{% url 'accountapp:logout' %}">
               Logout
            </a>

        </span>
        {% endif %}

    </div>

</div>